### ISSUE TITLE
not moving forward after sorting suffix array chunks and saving them to disk

### ISSUE THREAD

**Issue by MahejabeenNidhi** [ACSoupir/Genome_STAR_Index#1]
This my commandline

![2020-04-11](https://user-images.githubusercontent.com/52653630/79032544-fcf11880-7bd9-11ea-9922-8533bc9dad4b.png)

These are the instances I have running. I could delete the first one, that is where I had the sample files.

![2020-04-11 (1)](https://user-images.githubusercontent.com/52653630/79032658-ce277200-7bda-11ea-9a3e-3246afe907a5.png)

I suppose I could increase the number of threads to 12 because only 60% of CPU is being used

![2020-04-11 (2)](https://user-images.githubusercontent.com/52653630/79032661-d2538f80-7bda-11ea-9a6f-d4820391bbc3.png)

Thank you so so much again. What would your recommendations be?

**Comment by ACSoupir** [comment]
Hey. With it sorting the suffix array chunks, I think you just have to let it go. Running your genomes on my tower took a little over 2 hours. It was a little more than 30 minutes on the 80 core system.

One thing you can do to check individual CPU cores, and I would be careful and not try to rush it, is to do Ctrl + Z. It should pop up saying something like "[1]+ Stopped ..." This is good. It means that the command was PAUSED in the background. This can also be done right when executing the command the first time by added `&` to the end, like in the second image.

![image](https://user-images.githubusercontent.com/34483643/79032874-67b93a00-7b6f-11ea-9228-9f7d029a7810.png)

Then you can type in the terminal window `bg 1`, if the job number was 1. This will set the command running in the background so you can continue to work in the terminal. This background will be useful for the next part.

![image](https://user-images.githubusercontent.com/34483643/79032932-c1b9ff80-7b6f-11ea-8813-ccbbd3b25e57.png)

Now that STAR is running again in the background (this can be further checked by running `jobs` to display the jobs that are paused, running, or finished), you can type the `top` command to see how much cpu/memory each process is consuming. Since there are steps of STAR that are single threaded, they are the bottle neck of the whole thing.

Let me know if STAR isn't using any cpu. In that case we might need to try something else, otherwise if it is utilizing 100% of a core (indicated simply by `top` saying 100% or if it is using many cores it'll be 100+; mine said something like 7900% when using the big system) then I would let it go. Sometimes it takes a while.

**Comment by MahejabeenNidhi** [comment]
This is how it looks with top

![2020-04-11 (3)](https://user-images.githubusercontent.com/52653630/79033132-42174980-7bde-11ea-82c1-ef1c7a455f12.png)

**Comment by ACSoupir** [comment]
Yeah, great! That means STAR is still doing it's thing in the background. You can see it's allocated a little more than 24gb of RAM to STAR, and that STAR itself is using about 18gb while using 600%, or 6 cores. This looks good. Let it go for a while and see what happens.
What I always do is have 2 terminals open. The one that you currently have open is what you will need to use to go back and bring STAR to the foreground. To do this, you can close the top with Ctrl + C, then type `fg 1` to bring the STAR job to the foreground if the job number is 1. In this terminal you can keep track of where exactly  STAR is in its process without having to continually open the log file.
In a second terminal you can use the `top` command to keep an eye on the resource usage that STAR has. If STAR doesn't terminate in the first window, but isn't using any CPU in the `top` window, then I would worry. Otherwise You should be good!
